//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_CongViec
    {
        public F_CongViec()
        {
            this.F_LichSuLamViec = new HashSet<F_LichSuLamViec>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public string Sound { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<F_LichSuLamViec> F_LichSuLamViec { get; set; }
    }
}
