//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_LichSuLamViec
    {
        public int Id { get; set; }
        public int CVId { get; set; }
        public string Note { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual F_CongViec F_CongViec { get; set; }
    }
}
