//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VatTu
    {
        public VatTu()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }
    
        public int Id { get; set; }
        public string Ten { get; set; }
        public string CongDung { get; set; }
        public string CachDung { get; set; }
        public string DanhGia { get; set; }
        public double DonGia { get; set; }
        public string Image { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
    }
}
